
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.url.compis.proyectofas2;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int COMA = 3;
  public static final int NUM = 2;
  public static final int PD = 4;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "COMA",
  "PD"
  };
}

