
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.url.compis.proyectofas2;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NBOOL = 14;
  public static final int SQRT = 38;
  public static final int SEN = 34;
  public static final int CLIN = 40;
  public static final int MetRes = 28;
  public static final int POT = 48;
  public static final int CLPRPV = 24;
  public static final int OLOG = 57;
  public static final int CLPRPU = 22;
  public static final int RES = 59;
  public static final int CLPRPT = 23;
  public static final int P = 44;
  public static final int MYQ = 52;
  public static final int NUMR = 16;
  public static final int DSP = 63;
  public static final int DECR = 47;
  public static final int INCR = 46;
  public static final int INT = 5;
  public static final int TAN = 36;
  public static final int CLEX = 21;
  public static final int FRM = 10;
  public static final int ELS = 4;
  public static final int CL = 20;
  public static final int CADTXT = 18;
  public static final int BOOL = 7;
  public static final int FRH = 11;
  public static final int FLC = 56;
  public static final int DIV = 61;
  public static final int FRDEC = 13;
  public static final int NUM = 15;
  public static final int FRD = 9;
  public static final int RETN = 39;
  public static final int NMCL = 19;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int METPRIN = 29;
  public static final int RD = 41;
  public static final int error = 1;
  public static final int MUL = 60;
  public static final int COMA = 45;
  public static final int EQEQ = 50;
  public static final int SPC = 43;
  public static final int IMP = 30;
  public static final int MOD = 62;
  public static final int COS = 35;
  public static final int NEQ = 51;
  public static final int EQ = 49;
  public static final int CLMTPV = 27;
  public static final int CLMTPU = 25;
  public static final int CLMTPT = 26;
  public static final int LOG = 37;
  public static final int PDR = 55;
  public static final int WT = 42;
  public static final int IDEN = 17;
  public static final int MNQ = 53;
  public static final int FLOAT = 8;
  public static final int FcI = 32;
  public static final int SUM = 58;
  public static final int FcF = 31;
  public static final int STRING = 6;
  public static final int FRINC = 12;
  public static final int FcB = 33;
  public static final int THN = 3;
  public static final int PIZ = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THN",
  "ELS",
  "INT",
  "STRING",
  "BOOL",
  "FLOAT",
  "FRD",
  "FRM",
  "FRH",
  "FRINC",
  "FRDEC",
  "NBOOL",
  "NUM",
  "NUMR",
  "IDEN",
  "CADTXT",
  "NMCL",
  "CL",
  "CLEX",
  "CLPRPU",
  "CLPRPT",
  "CLPRPV",
  "CLMTPU",
  "CLMTPT",
  "CLMTPV",
  "MetRes",
  "METPRIN",
  "IMP",
  "FcF",
  "FcI",
  "FcB",
  "SEN",
  "COS",
  "TAN",
  "LOG",
  "SQRT",
  "RETN",
  "CLIN",
  "RD",
  "WT",
  "SPC",
  "P",
  "COMA",
  "INCR",
  "DECR",
  "POT",
  "EQ",
  "EQEQ",
  "NEQ",
  "MYQ",
  "MNQ",
  "PIZ",
  "PDR",
  "FLC",
  "OLOG",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "DSP"
  };
}

